#!/usr/bin/env python3
"""Render the web security policy for a real server.

    python3 tools/render-headers.py --server caddy
    python3 tools/render-headers.py --server nginx
    python3 tools/render-headers.py --check firebase.json

`deploy/web-headers.json` is the source of truth for the headers the dashboard is
served with: HSTS, a strict CSP with no `unsafe-inline` on the console,
`frame-ancestors 'none'`, and an exact `connect-src` list. All of that currently
lives inside `firebase.json`, and Firebase Hosting is retired from the target
architecture — so without somewhere else to keep it, the hardening would be
deleted along with the platform and rediscovered later, one incident at a time.

`--check` compares the canonical policy against `firebase.json` and fails on any
difference, so the two cannot drift while both exist. Once Firebase Hosting is
gone, `firebase.json` and that check go with it and this file stays.

The rendered output is deliberately a *snippet* rather than a whole server
configuration. TLS, listeners, roots and logging belong to whoever runs the
server; this only carries the part that is a security decision.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parent.parent
POLICY = ROOT / "deploy" / "web-headers.json"


def load_policy(path: pathlib.Path = POLICY) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return list(data["paths"])


def load_firebase(path: pathlib.Path) -> list[dict[str, Any]]:
    hosting = json.loads(path.read_text(encoding="utf-8"))["hosting"]
    return [
        {
            "path": entry["source"],
            "headers": {h["key"]: h["value"] for h in entry["headers"]},
        }
        for entry in hosting["headers"]
    ]


def differences(policy: list[dict[str, Any]], other: list[dict[str, Any]]) -> list[str]:
    """Every way the two disagree, named individually.

    Reported in full rather than stopping at the first, because whoever is
    reconciling them wants the list, not a game of twenty questions.
    """
    ours = {entry["path"]: entry["headers"] for entry in policy}
    theirs = {entry["path"]: entry["headers"] for entry in other}
    problems: list[str] = []

    for path in sorted(set(ours) | set(theirs)):
        if path not in theirs:
            problems.append(f"{path}: present in the policy, missing from firebase.json")
            continue
        if path not in ours:
            problems.append(f"{path}: present in firebase.json, missing from the policy")
            continue
        for key in sorted(set(ours[path]) | set(theirs[path])):
            mine, yours = ours[path].get(key), theirs[path].get(key)
            if mine is None:
                problems.append(f"{path}: {key} is in firebase.json but not the policy")
            elif yours is None:
                problems.append(f"{path}: {key} is in the policy but not firebase.json")
            elif " ".join(mine.split()) != " ".join(yours.split()):
                problems.append(f"{path}: {key} differs")
    return problems


# ── rendering ───────────────────────────────────────────────────────────────


def render_caddy(policy: list[dict[str, Any]]) -> str:
    lines = [
        "# Generated by tools/render-headers.py from deploy/web-headers.json.",
        "# Edit the policy, not this file. TLS, listeners and roots are not here",
        "# on purpose: this carries only the part that is a security decision.",
        "",
    ]
    for entry in policy:
        path, note = entry["path"], entry.get("note", "")
        if note:
            lines.append(f"# {note}")
        if path == "**":
            lines.append("header {")
        else:
            lines.append(f"@{path.strip('/').replace('.', '_').replace('/', '_')} path {path}")
            lines.append(f"header @{path.strip('/').replace('.', '_').replace('/', '_')} {{")
        for key, value in entry["headers"].items():
            lines.append(f'    {key} "{value}"')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def render_nginx(policy: list[dict[str, Any]]) -> str:
    lines = [
        "# Generated by tools/render-headers.py from deploy/web-headers.json.",
        "# Edit the policy, not this file.",
        "#",
        "# `always` on every add_header: without it nginx omits the header on error",
        "# responses, so a 404 or a 502 would be served without a CSP — and an error",
        "# page is exactly where injected content tends to end up.",
        "#",
        "# nginx does not inherit add_header into a location that sets its own, so the",
        "# baseline set is repeated inside each location block rather than assumed.",
        "",
    ]
    baseline: dict[str, Any] = next((e for e in policy if e["path"] == "**"), {"headers": {}})

    for key, value in baseline["headers"].items():
        lines.append(f'add_header {key} "{value}" always;')
    lines.append("")

    for entry in policy:
        if entry["path"] == "**":
            continue
        note = entry.get("note", "")
        if note:
            lines.append(f"# {note}")
        lines.append(f"location = {entry['path']} {{")
        for key, value in {**baseline["headers"], **entry["headers"]}.items():
            lines.append(f'    add_header {key} "{value}" always;')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


RENDERERS = {"caddy": render_caddy, "nginx": render_nginx}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="render-headers")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--server", choices=sorted(RENDERERS), help="render a config snippet")
    group.add_argument("--check", metavar="FIREBASE_JSON", help="compare against firebase.json")
    parser.add_argument("--policy", default=str(POLICY), help="policy file to read")
    args = parser.parse_args(argv)

    policy = load_policy(pathlib.Path(args.policy))

    if args.check:
        problems = differences(policy, load_firebase(pathlib.Path(args.check)))
        if problems:
            print("the header policy and firebase.json disagree:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            return 1
        print(f"header policy matches {args.check} across {len(policy)} path rule(s)")
        return 0

    print(RENDERERS[args.server](policy))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
